### ISSUE TITLE
Backend Master Issue

### ISSUE THREAD

**Issue by SamuelBeshara** [Sampler-Capstone/Backend#1]
- [ ] Pads
  - [ ] Receiving input from HW
  - [ ] Assigning a track to Pad
- [ ] Knobs
  - [ ] Receiving input from HW
  - [ ] Assigning a sound effect to Pad
- [ ] Producing
- [ ] Slicing
